language: php

branches:
  except:
    - /^release-.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/
    - $HOME/.local
    - laminas-mkdoc-theme

env:
  global:
    - SITE_URL: https://docs.laminas.dev/laminas-session
    - GH_USER_NAME: "Matthew Weier O'Phinney"
    - GH_USER_EMAIL: matthew@weierophinney.net
    - GH_REF: github.com/laminas/laminas-session.git
    - secure: "ig2TftPXHnxHzO9ho44sj5PnWfoKlHt6el7jzU80udzFIyhFBhgTGVC1I2kNLDJ8gvZitfuogxR/XYRMSTl2Pe/Te8hbza+PShlrqSG9C3PwApUof2BiuTNcIYjAp+RxQhjluKl/SmloUQhS8C1eb0WSnVfCjTQjlf+CIaJ+m1YaSVIkFjh3IyJgAglPdSB8Avst7xpYLaminas0cK723ZtyApUsuWoSHQjof54ziN+YDqWBfNovR1rWTmTNCfsBOHIhKTFhV0duXE+3MCnSTb3HogNtBuVKB842SU+8lnU1xaV7Ty3fE9nIB/j/mLC+MAGoZJshAv/o6ui3Y/41+oATllLgFnsy6+KvN6NiH449h2zMMy6cF3FILrYGpLpBafP3Yjxssdz9UaQtuNFRflGNpcoDAkw0x7+w5vX+yH7qibW4HQqyZLxeefZ22+F6NRPmsanJdPtZ7LKHMani3lNq9zWetNL8XaREwclSDK50HHhIygMAejr0OU5fVHmk30yZqGdiEcAoiabwgENt7ndeQPW6u3OOfzteo7dDZwWdZLbB1JWFmYbwQH4ek7KTIpQ8utH53qwg2PeLYg0W0y4g9Y46gGzaBIlsEE6RAIE8b8O3f6dPzRtTuHTJCS+AGQX61bqQUsph9jEIBsmVTVUHXNmLmOZnthPbzpPfza8v3EQM="

services:
  - mongodb

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - CS_CHECK=true
    - php: 5.5
      env:
        - EVENT_MANAGER_VERSION="^2.6.2"
        - SERVICE_MANAGER_VERSION="^2.7.5"
    - php: 5.6
      env:
        - TEST_COVERAGE=true
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 5.6
      env:
        - TEST_COVERAGE=true
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 5.6
      env:
        - EVENT_MANAGER_VERSION="^2.6.2"
        - SERVICE_MANAGER_VERSION="^2.7.5"
    - php: 7
    - php: 7
      env:
        - EVENT_MANAGER_VERSION="^2.6.2"
        - SERVICE_MANAGER_VERSION="^2.7.5"
    - php: 7.1
    - php: 7.1
      env:
        - EVENT_MANAGER_VERSION="^2.6.2"
        - SERVICE_MANAGER_VERSION="^2.7.5"
    - php: hhvm
    - php: hhvm
      env:
        - EVENT_MANAGER_VERSION="^2.6.2"
        - SERVICE_MANAGER_VERSION="^2.7.5"
  allow_failures:
    - php: hhvm

before_install:
  - pecl -q install mongodb
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi
  - if [[ $EVENT_MANAGER_VERSION != '' ]]; then composer require --no-update "laminas/laminas-eventmanager:$EVENT_MANAGER_VERSION" ; fi
  - if [[ $EVENT_MANAGER_VERSION == '' ]]; then composer require --no-update "laminas/laminas-eventmanager:^3.0" ; fi
  - if [[ $SERVICE_MANAGER_VERSION != '' ]]; then composer require --dev --no-update "laminas/laminas-servicemanager:$SERVICE_MANAGER_VERSION" ; fi
  - if [[ $SERVICE_MANAGER_VERSION == '' ]]; then composer require --dev --no-update "laminas/laminas-servicemanager:^3.0.3" ; fi

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then wget -O theme-installer.sh "https://raw.githubusercontent.com/laminas/laminas-mkdoc-theme/master/theme-installer.sh" ; chmod 755 theme-installer.sh ; ./theme-installer.sh ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; ./laminas-mkdoc-theme/deploy.sh ; echo "Completed deploying documentation" ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer upload-coverage ; fi

notifications:
  email: false
  slack:
    rooms:
      - secure:  "MlhbWQ2bxDu9dmQ7o2v/WwwAedl57SVVew0XN/Wvbnt1Q8DY+kBGVxmV7DzurOG0iiq7pzYySNgdyqKpE/2g1IhWD7txrT9BCSq0xPk4i+AUn4xMViZKCVkPYhaFo9K3Z1HnPJPfcnDz075umGKWhfip12LSIMkXRqkNANgKLZ3ouDFRRG1NL7bOmW8GDIAcF3TpIDCy9L+awnGMHTtSO6M1jtueksQpBH7ESosrtkferzNVeV2USvzZbzI04PQ9vsrOOZnkqXgNsk3+gMvZNw6PbCk3eOmgGyFaygpL1NXi3VV6sK6SFtwiuwAiEhiFudOnovpE/90HKtWyCISSSGMlUHF6trEVGR0tQxuw+Du1HNrBhiWZHj6vdMpNdZSEqwBEbCeO5LAHM9fKDIT2utQQXrk62julZCvnAupImgBl5IswlO6f/cGv8/cesLulyc9t6L0LCuuXG2xK/WPSCOtkFB4nuOgNNNXhkljyrYxi8poXGa+4SupqCMA0iNPeUB6NnyCMrBCbUnjEjNIGMezx7ELIoepJuw66py6smigYGyrVXhodlGPvr7jaXVjYHNbDadHA55Vk6tRgYwTZclnrSn8sU3jI3xW/a6APkwQMd40yc+GAy5F72jpONiXeB7f8UG+d4qoWH4doBJii+cb/tVroH1tFDlfTSa5XRec="
    on_success: change
    on_failure: always
