docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Reference:
        - "Session Config": config.md
        - "Session Container": container.md
        - "Session Manager": manager.md
        - "Session Save Handlers": save-handler.md
        - "Session Storage": storage.md
        - "Session Validators": validator.md
site_name: laminas-session
site_description: laminas-session
repo_url: 'https://github.com/laminas/laminas-session'
